services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    disk:
      sizeGB: 1
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:GeneratedAppKeyHere
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://your-app-name.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-database-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-database-username
      - key: DB_PASSWORD
        value: your-database-password
